package fr.afcepf.al22.riaserveur2.entity;

// Generated 21 févr. 2015 10:38:14 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Personne generated by hbm2java
 */
@Entity
@Table(name = "personne"
		, catalog = "ria")
public class Personne implements java.io.Serializable {

	private Integer id;
	private String libelle;
	private Set<Repas> repases = new HashSet<Repas>();

	public Personne() {
	}

	public Personne(String libelle, Set<Repas> repases) {
		this.libelle = libelle;
		this.repases = repases;
	}

	public Personne(String libelle) {
		this.libelle = libelle;
	}

	public Personne(Integer id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "libelle", length = 45)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personne")
	public Set<Repas> getRepases() {
		return this.repases;
	}

	public void setRepases(Set<Repas> repases) {
		this.repases = repases;
	}

	@Override
	public String toString() {
		return "Personne [id=" + id + ", libelle=" + libelle + ", repases=\n" + repases + "]\n";
	}

}
